spring.application.name=agenteqaIA
# MongoDB
spring.data.mongodb.uri=${MONGO_URI_NUVEM}
spring.data.mongodb.database=${MONGODB_DATABASE}

# OpenAI
openai.api.key=${OPENAI_API_KEY}

# Porta padrão
server.port=8089


spring.profiles.active=default
